
# BEGIN ANSIBLE MANAGED BLOCK

p2p_ip:
  mxp01:
    - {port: ge-0/0/0, ip: 10.1.1.2 , peer: mxpe01, pport: ge-0/0/0, peer_ip: 10.1.1.3}
    - {port: ge-0/0/1, ip: 10.1.1.4 , peer: mxpe02, pport: ge-0/0/0, peer_ip: 10.1.1.5}
    - {port: ge-0/0/2, ip: 10.1.1.6 , peer: xrpe03, pport: GigabitEthernet0/0/0/0, peer_ip: 10.1.1.7}
    - {port: ge-0/0/3, ip: 10.1.1.0 , peer: mxp02, pport: ge-0/0/3, peer_ip: 10.1.1.1}
  mxp02:
    - {port: ge-0/0/0, ip: 10.1.1.8 , peer: mxpe01, pport: ge-0/0/1, peer_ip: 10.1.1.9}
    - {port: ge-0/0/1, ip: 10.1.1.10 , peer: mxpe02, pport: ge-0/0/1, peer_ip: 10.1.1.11}
    - {port: ge-0/0/2, ip: 10.1.1.12 , peer: xrpe03, pport: GigabitEthernet0/0/0/1, peer_ip: 10.1.1.13}
    - {port: ge-0/0/3, ip: 10.1.1.1 , peer: mxp01, pport: ge-0/0/3, peer_ip: 10.1.1.0}
  mxpe01:
    - {port: ge-0/0/0, ip: 10.1.1.3 , peer: mxp01, pport: ge-0/0/0, peer_ip: 10.1.1.2}
    - {port: ge-0/0/1, ip: 10.1.1.9 , peer: mxp02, pport: ge-0/0/0, peer_ip: 10.1.1.8}
  mxpe02:
    - {port: ge-0/0/0, ip: 10.1.1.5 , peer: mxp01, pport: ge-0/0/1, peer_ip: 10.1.1.4}
    - {port: ge-0/0/1, ip: 10.1.1.11 , peer: mxp02, pport: ge-0/0/1, peer_ip: 10.1.1.10}
  xrpe03:
    - {port: GigabitEthernet0/0/0/0, ip: 10.1.1.7/31 , peer: mxp01, pport: ge-0/0/2, peer_ip: 10.1.1.6/31}
    - {port: GigabitEthernet0/0/0/1, ip: 10.1.1.13/31 , peer: mxp02, pport: ge-0/0/2, peer_ip: 10.1.1.12/31}

lo_ip:
  mxp01: 10.100.1.254/32
  mxp02: 10.100.1.253/32
  mxpe01: 10.100.1.1/32
  mxpe02: 10.100.1.2/32
  xrpe03: 10.100.1.3/32

# END ANSIBLE MANAGED BLOCK
